language: node_js

sudo: false

node_js:
  - 'stable'

install: npm install

script:
  - echo "Running tests against $(node -v)..."
  - npm run test:integration
  - npm run test:unit

after_script:
  - npm run coverage
  - cat ./coverage/lcov.info | coveralls

services:
  - mongodb